// ermine-props.generated.ts — generated by surfaces/typed/generate.ts — do not edit.
// One-word-per-axis is TYPE-enforced for single props and for the whole-vs-dial
// exclusions below; everything else is the runtime linter's job (see ENFORCEMENT.md).

export type SizeStep = "sm" | "md" | "lg" | "xl" | "2xl";
export type SpacingStep = "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
export type DurationStep = "quick" | "settled";

type None<K extends PropertyKey> = { [P in K]?: never };

// props with no cross-prop exclusion (single prop = single word: P1 by construction)
export interface ErminePlainProps {
  /** axis `structure` */
  structure?: "horizontal" | "vertical" | "grid" | `grid-fit-${SizeStep}` | "columns-12" | "subgrid";
  /** axis `m1-flow-participation` */
  flowParticipation?: "inline" | "boxed" | "boxed-inline";
  /** axis `m3-self-size` */
  selfSize?: "basis-content" | "basis-ratio" | `basis-exact-${SizeStep}`;
  /** axis `m4-self-alignment` */
  selfAlignment?: "self-start" | "self-center" | "self-end" | "self-stretch" | "self-baseline";
  /** axis `m5-grid-placement` */
  gridPlacement?: `span-${number}` | `row-span-${number}` | "span-all" | "half" | "third" | "quarter" | "two-thirds" | "three-quarters" | "sixth";
  /** axis `density` */
  gap?: SpacingStep;
  /** axis `flow-spacing` */
  flow?: SpacingStep;
  /** axis `push` */
  push?: "push";
  /** axis `alignment-container` */
  align?: "align-start" | "align-center" | "align-end" | "align-stretch" | "align-baseline";
  /** axis `alignment-container` */
  justify?: "justify-start" | "justify-center" | "justify-end" | "justify-between" | "justify-around";
  /** axis `divider` */
  divider?: "divided" | "undivided";
  /** axis `wrapping` */
  wrapping?: "wrap-allowed" | "wrap-prevent" | "wrap-reverse";
  /** axis `constraints` */
  minWidth?: SizeStep;
  /** axis `constraints` */
  maxWidth?: SizeStep;
  /** axis `constraints` */
  minHeight?: SizeStep;
  /** axis `constraints` */
  maxHeight?: SizeStep;
  /** axis `aspect` */
  aspect?: "square";
  /** axis `cover` */
  cover?: "cover";
  /** axis `positioned-centering` */
  positionedCentering?: "center-x" | "center-y";
  /** axis `viewport-fill` */
  viewportFill?: "fill-viewport";
  /** axis `z-scale` */
  zScale?: "base" | "content" | "raised" | "dropdown" | "sticky" | "tooltip";
  /** axis `top-layer-mechanism` */
  topLayerMechanism?: "overlay" | "modal" | "popover" | "toast";
  /** axis `position-mode` */
  positionMode?: "position-static" | "position-relative" | "position-absolute" | "position-fixed" | "position-sticky";
  /** axis `stacking-context` */
  stackingContext?: "isolate";
  /** axis `tween` */
  tween?: DurationStep;
  /** axis `motion-micro` */
  motionMicro?: "decelerate" | "accelerate" | "standard" | "emphasized" | "symmetric" | "asymmetric";
  /** axis `motion-macro` */
  motionMacro?: "together" | "sequence" | "cascade";
  /** axis `effect` */
  effect?: "shake";
  /** axis `state.focus` */
  focus?: "hover" | "focus" | "focus-visible" | "active" | readonly ("hover" | "focus" | "focus-visible" | "active")[];
  /** axis `state.selection` */
  selection?: "selectable" | "selected" | "checked-mixed" | "current-page" | "current-step" | "current-location" | "current-date" | "current-time" | "current-true" | readonly ("selectable" | "selected" | "checked-mixed" | "current-page" | "current-step" | "current-location" | "current-date" | "current-time" | "current-true")[];
  /** axis `state.availability` */
  availability?: "disabled" | "read-only" | "busy" | readonly ("disabled" | "read-only" | "busy")[];
  /** axis `state.disclosure` */
  disclosure?: "expanded" | "open";
  /** axis `state.validity` */
  validity?: "invalid" | "user-invalid" | "required" | "out-of-range" | readonly ("invalid" | "user-invalid" | "required" | "out-of-range")[];
  /** axis `state.sort` */
  sort?: "sorted-none" | "sorted-ascending" | "sorted-descending" | readonly ("sorted-none" | "sorted-ascending" | "sorted-descending")[];
  /** axis `state.drag` */
  drag?: "dragging" | readonly ("dragging")[];
  /** axis `state.continuous-input` */
  continuousInput?: "scroll-progress" | "drag-progress" | readonly ("scroll-progress" | "drag-progress")[];
  /** axis `state.relational` */
  relational?: "active-descendant" | readonly ("active-descendant")[];
  /** axis `skin-ground` */
  skinGround?: "ground" | "ground-subtle" | "ground-defined" | "ground-hover" | "ground-active" | "ground-selected" | "ground-accent" | "ground-accent-soft" | "ground-accent-faint" | "ground-pass" | "ground-pass-faint" | "ground-warn" | "ground-warn-faint" | "ground-fail" | "ground-fail-faint" | "ground-note" | "ground-note-faint";
  /** axis `skin-ink` */
  skinInk?: "ink" | "ink-soft" | "ink-muted" | "ink-faint" | "ink-inverse" | "ink-selected" | "ink-accent" | "ink-accent-soft" | "ink-accent-faint" | "ink-pass" | "ink-pass-faint" | "ink-warn" | "ink-warn-faint" | "ink-fail" | "ink-fail-faint" | "ink-note" | "ink-note-faint";
  /** axis `skin-rule` */
  skinRule?: "rule" | "rule-soft" | "rule-accent" | "rule-accent-soft" | "rule-accent-faint" | "rule-pass" | "rule-pass-faint" | "rule-warn" | "rule-warn-faint" | "rule-fail" | "rule-fail-faint" | "rule-note" | "rule-note-faint";
  /** axis `corner` */
  corner?: "corner-sm" | "corner-md" | "corner-lg" | "corner-xl" | "corner-2xl" | "corner-3xl";
  /** axis `rule-presence` */
  rulePresence?: "ruled" | "ruled-top" | "ruled-bottom" | "ruled-left" | "ruled-right";
  /** axis `font-size` */
  fontSize?: "font-xs" | "font-sm" | "font-md" | "font-lg" | "font-xl" | "font-2xl" | "font-3xl";
  /** axis `font-weight` */
  fontWeight?: "font-medium" | "font-semibold" | "font-bold";
  /** axis `font-family` */
  fontFamily?: "font-mono";
  /** axis `text-align` */
  textAlign?: "text-start" | "text-center";
  /** axis `elevation` */
  elevation?: "elevated";
  /** axis `affordance` */
  affordance?: "pressable";
  /** axis `concealment` */
  concealment?: "concealed" | "revealed";
  /** axis `numeric` */
  numeric?: "tabular";
  /** axis `type-label` */
  typeLabel?: "overline";
  /** axis `scrollbar` */
  scrollbar?: "scrollbar-subtle";
  /** axis `focus-ring` */
  focusRing?: "ring";
  /** axis `truncation` */
  truncation?: "truncate" | `clamp-${number}`;
  /** axis `selection-treatment` */
  selectionTreatment?: "selection-subtle" | "selection-strong";
}

// axis `m2-flex`: a whole-axis value fixes every dial — combining is a COMPILE error (P1/P5)
export type FlexExclusive =
  | ({ flex?: "rigid" | "compressible" | "expandable" | "elastic"; } & None<"grow" | "shrink">)
  | ({ grow?: number; shrink?: number; } & None<"flex">);

// axis `padding`: a whole-axis value fixes every dial — combining is a COMPILE error (P1/P5)
export type PaddingExclusive =
  | ({ padding?: SpacingStep; } & None<"paddingInline" | "paddingBlock">)
  | ({ paddingInline?: SpacingStep; paddingBlock?: SpacingStep; } & None<"padding">);

// axis `margin`: a whole-axis value fixes every dial — combining is a COMPILE error (P1/P5)
export type MarginExclusive =
  | ({ margin?: SpacingStep; } & None<"marginInline" | "marginBlock">)
  | ({ marginInline?: SpacingStep; marginBlock?: SpacingStep; } & None<"margin">);

// axis `overflow`: a whole-axis value fixes every dial — combining is a COMPILE error (P1/P5)
export type OverflowExclusive =
  | ({ overflow?: "scroll-auto" | "clip" | "hidden"; } & None<"overflowX" | "overflowY">)
  | ({ overflowX?: "scroll-x"; overflowY?: "scroll-y"; } & None<"overflow">);

// axis `fill`: a whole-axis value fixes every dial — combining is a COMPILE error (P1/P5)
export type FillExclusive =
  | ({ fill?: "fill"; } & None<"fillInline" | "fillBlock">)
  | ({ fillInline?: "fill-inline" | "hug-inline"; fillBlock?: "fill-block"; } & None<"fill">);

// base surface: everything except environment scopes
export type ErmineBaseProps = ErminePlainProps & FlexExclusive & PaddingExclusive & MarginExclusive & OverflowExclusive & FillExclusive;

// environment scopes hold BASE props only — a scoped word cannot itself be scoped
export interface ErmineScopeProps {
  /** scope prefix `viewport-sm:` */
  viewportSm?: ErmineBaseProps;
  /** scope prefix `viewport-md:` */
  viewportMd?: ErmineBaseProps;
  /** scope prefix `viewport-lg:` */
  viewportLg?: ErmineBaseProps;
  /** scope prefix `viewport-xl:` */
  viewportXl?: ErmineBaseProps;
  /** scope prefix `viewport-portrait:` */
  viewportPortrait?: ErmineBaseProps;
  /** scope prefix `viewport-landscape:` */
  viewportLandscape?: ErmineBaseProps;
  /** scope prefix `container-sm:` */
  containerSm?: ErmineBaseProps;
  /** scope prefix `container-md:` */
  containerMd?: ErmineBaseProps;
  /** scope prefix `container-lg:` */
  containerLg?: ErmineBaseProps;
  /** scope prefix `container-xl:` */
  containerXl?: ErmineBaseProps;
  /** scope prefix `prefers-reduced-motion:` */
  prefersReducedMotion?: ErmineBaseProps;
  /** scope prefix `prefers-color-scheme-dark:` */
  prefersColorSchemeDark?: ErmineBaseProps;
  /** scope prefix `prefers-contrast-more:` */
  prefersContrastMore?: ErmineBaseProps;
  /** scope prefix `prefers-reduced-transparency:` */
  prefersReducedTransparency?: ErmineBaseProps;
}

export type ErmineProps = ErmineBaseProps & ErmineScopeProps;

// runtime descriptors, in canonical (registry) order — toClassString walks these
export interface PropDescriptor { prop: string; axis: string; kind: "word" | "step-prefix" | "number-prefix" | "group"; prefix?: string; many?: boolean }
export const BASE_DESCRIPTORS: readonly PropDescriptor[] = [
  { prop: "structure", axis: "structure", kind: "word" },
  { prop: "flowParticipation", axis: "m1-flow-participation", kind: "word" },
  { prop: "flex", axis: "m2-flex", kind: "word" },
  { prop: "grow", axis: "m2-flex", kind: "number-prefix", prefix: "grow" },
  { prop: "shrink", axis: "m2-flex", kind: "number-prefix", prefix: "shrink" },
  { prop: "selfSize", axis: "m3-self-size", kind: "word" },
  { prop: "selfAlignment", axis: "m4-self-alignment", kind: "word" },
  { prop: "gridPlacement", axis: "m5-grid-placement", kind: "word" },
  { prop: "gap", axis: "density", kind: "step-prefix", prefix: "gap" },
  { prop: "flow", axis: "flow-spacing", kind: "step-prefix", prefix: "flow" },
  { prop: "padding", axis: "padding", kind: "step-prefix", prefix: "padding" },
  { prop: "paddingInline", axis: "padding", kind: "step-prefix", prefix: "padding-inline" },
  { prop: "paddingBlock", axis: "padding", kind: "step-prefix", prefix: "padding-block" },
  { prop: "margin", axis: "margin", kind: "step-prefix", prefix: "margin" },
  { prop: "marginInline", axis: "margin", kind: "step-prefix", prefix: "margin-inline" },
  { prop: "marginBlock", axis: "margin", kind: "step-prefix", prefix: "margin-block" },
  { prop: "push", axis: "push", kind: "word" },
  { prop: "align", axis: "alignment-container", kind: "word" },
  { prop: "justify", axis: "alignment-container", kind: "word" },
  { prop: "divider", axis: "divider", kind: "word" },
  { prop: "wrapping", axis: "wrapping", kind: "word" },
  { prop: "overflow", axis: "overflow", kind: "word" },
  { prop: "overflowX", axis: "overflow", kind: "word" },
  { prop: "overflowY", axis: "overflow", kind: "word" },
  { prop: "minWidth", axis: "constraints", kind: "step-prefix", prefix: "min-width" },
  { prop: "maxWidth", axis: "constraints", kind: "step-prefix", prefix: "max-width" },
  { prop: "minHeight", axis: "constraints", kind: "step-prefix", prefix: "min-height" },
  { prop: "maxHeight", axis: "constraints", kind: "step-prefix", prefix: "max-height" },
  { prop: "fill", axis: "fill", kind: "word" },
  { prop: "fillInline", axis: "fill", kind: "word" },
  { prop: "fillBlock", axis: "fill", kind: "word" },
  { prop: "aspect", axis: "aspect", kind: "word" },
  { prop: "cover", axis: "cover", kind: "word" },
  { prop: "positionedCentering", axis: "positioned-centering", kind: "word" },
  { prop: "viewportFill", axis: "viewport-fill", kind: "word" },
  { prop: "zScale", axis: "z-scale", kind: "word" },
  { prop: "topLayerMechanism", axis: "top-layer-mechanism", kind: "word" },
  { prop: "positionMode", axis: "position-mode", kind: "word" },
  { prop: "stackingContext", axis: "stacking-context", kind: "word" },
  { prop: "tween", axis: "tween", kind: "step-prefix", prefix: "tween" },
  { prop: "motionMicro", axis: "motion-micro", kind: "word" },
  { prop: "motionMacro", axis: "motion-macro", kind: "word" },
  { prop: "effect", axis: "effect", kind: "word" },
  { prop: "focus", axis: "state.focus", kind: "group", many: true },
  { prop: "selection", axis: "state.selection", kind: "group", many: true },
  { prop: "availability", axis: "state.availability", kind: "group", many: true },
  { prop: "disclosure", axis: "state.disclosure", kind: "group" },
  { prop: "validity", axis: "state.validity", kind: "group", many: true },
  { prop: "sort", axis: "state.sort", kind: "group", many: true },
  { prop: "drag", axis: "state.drag", kind: "group", many: true },
  { prop: "continuousInput", axis: "state.continuous-input", kind: "group", many: true },
  { prop: "relational", axis: "state.relational", kind: "group", many: true },
  { prop: "skinGround", axis: "skin-ground", kind: "word" },
  { prop: "skinInk", axis: "skin-ink", kind: "word" },
  { prop: "skinRule", axis: "skin-rule", kind: "word" },
  { prop: "corner", axis: "corner", kind: "word" },
  { prop: "rulePresence", axis: "rule-presence", kind: "word" },
  { prop: "fontSize", axis: "font-size", kind: "word" },
  { prop: "fontWeight", axis: "font-weight", kind: "word" },
  { prop: "fontFamily", axis: "font-family", kind: "word" },
  { prop: "textAlign", axis: "text-align", kind: "word" },
  { prop: "elevation", axis: "elevation", kind: "word" },
  { prop: "affordance", axis: "affordance", kind: "word" },
  { prop: "concealment", axis: "concealment", kind: "word" },
  { prop: "numeric", axis: "numeric", kind: "word" },
  { prop: "typeLabel", axis: "type-label", kind: "word" },
  { prop: "scrollbar", axis: "scrollbar", kind: "word" },
  { prop: "focusRing", axis: "focus-ring", kind: "word" },
  { prop: "truncation", axis: "truncation", kind: "word" },
  { prop: "selectionTreatment", axis: "selection-treatment", kind: "word" },
];

export const SCOPE_DESCRIPTORS: readonly { prop: string; prefix: string }[] = [
  { prop: "viewportSm", prefix: "viewport-sm" },
  { prop: "viewportMd", prefix: "viewport-md" },
  { prop: "viewportLg", prefix: "viewport-lg" },
  { prop: "viewportXl", prefix: "viewport-xl" },
  { prop: "viewportPortrait", prefix: "viewport-portrait" },
  { prop: "viewportLandscape", prefix: "viewport-landscape" },
  { prop: "containerSm", prefix: "container-sm" },
  { prop: "containerMd", prefix: "container-md" },
  { prop: "containerLg", prefix: "container-lg" },
  { prop: "containerXl", prefix: "container-xl" },
  { prop: "prefersReducedMotion", prefix: "prefers-reduced-motion" },
  { prop: "prefersColorSchemeDark", prefix: "prefers-color-scheme-dark" },
  { prop: "prefersContrastMore", prefix: "prefers-contrast-more" },
  { prop: "prefersReducedTransparency", prefix: "prefers-reduced-transparency" },
];

export const XOR_PROPS: ReadonlySet<string> = new Set(["flex","grow","shrink","padding","paddingInline","paddingBlock","margin","marginInline","marginBlock","overflow","overflowX","overflowY","fill","fillInline","fillBlock"]);
