// ermine-props.generated.ts — generated by surfaces/typed/generate.ts — do not edit.
// One-word-per-axis is TYPE-enforced for single props and for the whole-vs-dial
// exclusions below; everything else is the runtime linter's job (see ENFORCEMENT.md).
// Axes with no sanctioned vocabulary (gap-reported): skin-surface, skin-type — no props generated.

export type SizeStep = "sm" | "md" | "lg" | "xl";
export type DensityStep = "tight" | "snug" | "comfortable" | "relaxed" | "loose" | "separated";

type None<K extends PropertyKey> = { [P in K]?: never };

// props with no cross-prop exclusion (single prop = single word: P1 by construction)
export interface ErminePlainProps {
  /** axis `structure` */
  structure?: "horizontal" | "vertical" | "grid";
  /** axis `m1-flow-participation` */
  flowParticipation?: "inline" | "boxed" | "boxed-inline";
  /** axis `m3-self-size` */
  selfSize?: "basis-content" | "basis-ratio" | `basis-exact-${SizeStep}`;
  /** axis `m4-self-alignment` */
  selfAlignment?: "self-start" | "self-center" | "self-end" | "self-stretch" | "self-baseline";
  /** axis `m5-grid-placement` */
  gridPlacement?: `span-${number}` | `row-span-${number}` | "span-all";
  /** axis `density` */
  gap?: DensityStep;
  /** axis `flow-spacing` */
  flow?: DensityStep;
  /** axis `alignment-container` */
  align?: "align-start" | "align-center" | "align-end" | "align-stretch" | "align-baseline";
  /** axis `alignment-container` */
  justify?: "justify-start" | "justify-center" | "justify-end" | "justify-between" | "justify-around";
  /** axis `divider` */
  divider?: "divided" | "undivided";
  /** axis `wrapping` */
  wrapping?: "wrap-allowed" | "wrap-prevent" | "wrap-reverse";
  /** axis `constraints` */
  minWidth?: SizeStep;
  /** axis `constraints` */
  maxWidth?: SizeStep;
  /** axis `constraints` */
  minHeight?: SizeStep;
  /** axis `constraints` */
  maxHeight?: SizeStep;
  /** axis `z-scale` */
  zScale?: "base" | "content" | "raised" | "dropdown" | "sticky" | "tooltip";
  /** axis `top-layer-mechanism` */
  topLayerMechanism?: "overlay" | "modal" | "popover" | "toast";
  /** axis `position-mode` */
  positionMode?: "position-static" | "position-relative" | "position-absolute" | "position-fixed" | "position-sticky";
  /** axis `stacking-context` */
  stackingContext?: "isolate";
  /** axis `motion-micro` */
  motionMicro?: "decelerate" | "accelerate" | "standard" | "emphasized" | "symmetric" | "asymmetric";
  /** axis `motion-macro` */
  motionMacro?: "together" | "sequence" | "cascade";
  /** axis `state.focus` */
  focus?: "hover" | "focus" | "focus-visible" | "active" | readonly ("hover" | "focus" | "focus-visible" | "active")[];
  /** axis `state.selection` */
  selection?: "selectable" | "selected" | "checked-mixed" | "current-page" | "current-step" | "current-location" | "current-date" | "current-time" | "current-true" | readonly ("selectable" | "selected" | "checked-mixed" | "current-page" | "current-step" | "current-location" | "current-date" | "current-time" | "current-true")[];
  /** axis `state.availability` */
  availability?: "disabled" | "read-only" | "busy" | readonly ("disabled" | "read-only" | "busy")[];
  /** axis `state.disclosure` */
  disclosure?: "expanded" | "open";
  /** axis `state.validity` */
  validity?: "invalid" | "user-invalid" | "required" | "out-of-range" | readonly ("invalid" | "user-invalid" | "required" | "out-of-range")[];
  /** axis `state.sort` */
  sort?: "sorted-none" | "sorted-ascending" | "sorted-descending" | readonly ("sorted-none" | "sorted-ascending" | "sorted-descending")[];
  /** axis `state.drag` */
  drag?: "dragging" | readonly ("dragging")[];
  /** axis `state.continuous-input` */
  continuousInput?: "scroll-progress" | "drag-progress" | readonly ("scroll-progress" | "drag-progress")[];
  /** axis `state.relational` */
  relational?: "active-descendant" | readonly ("active-descendant")[];
  /** axis `skin-ground` */
  skinGround?: "ground" | "ground-subtle" | "ground-defined" | "ground-hover" | "ground-active" | "ground-selected" | "ground-accent" | "ground-accent-soft" | "ground-accent-faint" | "ground-pass" | "ground-pass-faint" | "ground-warn" | "ground-warn-faint" | "ground-fail" | "ground-fail-faint" | "ground-note" | "ground-note-faint";
  /** axis `skin-ink` */
  skinInk?: "ink" | "ink-soft" | "ink-muted" | "ink-faint" | "ink-inverse" | "ink-selected" | "ink-accent" | "ink-accent-soft" | "ink-accent-faint" | "ink-pass" | "ink-pass-faint" | "ink-warn" | "ink-warn-faint" | "ink-fail" | "ink-fail-faint" | "ink-note" | "ink-note-faint";
  /** axis `skin-rule` */
  skinRule?: "rule" | "rule-soft" | "rule-accent" | "rule-accent-soft" | "rule-accent-faint" | "rule-pass" | "rule-pass-faint" | "rule-warn" | "rule-warn-faint" | "rule-fail" | "rule-fail-faint" | "rule-note" | "rule-note-faint";
  /** axis `corner` */
  corner?: "corner-sm" | "corner-md" | "corner-lg" | "corner-xl" | "corner-2xl" | "corner-3xl";
  /** axis `font-size` */
  fontSize?: "font-xs" | "font-sm" | "font-md" | "font-lg" | "font-xl" | "font-2xl" | "font-3xl";
  /** axis `font-weight` */
  fontWeight?: "font-medium" | "font-semibold" | "font-bold";
  /** axis `selection-treatment` */
  selectionTreatment?: "selection-subtle" | "selection-strong";
}

// axis `m2-flex`: a whole-axis value fixes every dial — combining is a COMPILE error (P1/P5)
export type FlexExclusive =
  | ({ flex?: "rigid" | "compressible" | "expandable" | "elastic"; } & None<"grow" | "shrink">)
  | ({ grow?: number; shrink?: number; } & None<"flex">);

// axis `padding`: a whole-axis value fixes every dial — combining is a COMPILE error (P1/P5)
export type PaddingExclusive =
  | ({ padding?: DensityStep; } & None<"paddingInline" | "paddingBlock">)
  | ({ paddingInline?: DensityStep; paddingBlock?: DensityStep; } & None<"padding">);

// axis `margin`: a whole-axis value fixes every dial — combining is a COMPILE error (P1/P5)
export type MarginExclusive =
  | ({ margin?: DensityStep; } & None<"marginInline" | "marginBlock">)
  | ({ marginInline?: DensityStep; marginBlock?: DensityStep; } & None<"margin">);

// axis `overflow`: a whole-axis value fixes every dial — combining is a COMPILE error (P1/P5)
export type OverflowExclusive =
  | ({ overflow?: "scroll-auto" | "clip"; } & None<"overflowX" | "overflowY">)
  | ({ overflowX?: "scroll-x"; overflowY?: "scroll-y"; } & None<"overflow">);

// base surface: everything except environment scopes
export type ErmineBaseProps = ErminePlainProps & FlexExclusive & PaddingExclusive & MarginExclusive & OverflowExclusive;

// environment scopes hold BASE props only — a scoped word cannot itself be scoped
export interface ErmineScopeProps {
  /** scope prefix `viewport-sm:` */
  viewportSm?: ErmineBaseProps;
  /** scope prefix `viewport-md:` */
  viewportMd?: ErmineBaseProps;
  /** scope prefix `viewport-lg:` */
  viewportLg?: ErmineBaseProps;
  /** scope prefix `viewport-xl:` */
  viewportXl?: ErmineBaseProps;
  /** scope prefix `viewport-portrait:` */
  viewportPortrait?: ErmineBaseProps;
  /** scope prefix `viewport-landscape:` */
  viewportLandscape?: ErmineBaseProps;
  /** scope prefix `container-sm:` */
  containerSm?: ErmineBaseProps;
  /** scope prefix `container-md:` */
  containerMd?: ErmineBaseProps;
  /** scope prefix `container-lg:` */
  containerLg?: ErmineBaseProps;
  /** scope prefix `container-xl:` */
  containerXl?: ErmineBaseProps;
  /** scope prefix `prefers-reduced-motion:` */
  prefersReducedMotion?: ErmineBaseProps;
  /** scope prefix `prefers-color-scheme-dark:` */
  prefersColorSchemeDark?: ErmineBaseProps;
  /** scope prefix `prefers-contrast-more:` */
  prefersContrastMore?: ErmineBaseProps;
  /** scope prefix `prefers-reduced-transparency:` */
  prefersReducedTransparency?: ErmineBaseProps;
}

export type ErmineProps = ErmineBaseProps & ErmineScopeProps;

// runtime descriptors, in canonical (registry) order — toClassString walks these
export interface PropDescriptor { prop: string; axis: string; kind: "word" | "step-prefix" | "number-prefix" | "group"; prefix?: string; many?: boolean }
export const BASE_DESCRIPTORS: readonly PropDescriptor[] = [
  { prop: "structure", axis: "structure", kind: "word" },
  { prop: "flowParticipation", axis: "m1-flow-participation", kind: "word" },
  { prop: "flex", axis: "m2-flex", kind: "word" },
  { prop: "grow", axis: "m2-flex", kind: "number-prefix", prefix: "grow" },
  { prop: "shrink", axis: "m2-flex", kind: "number-prefix", prefix: "shrink" },
  { prop: "selfSize", axis: "m3-self-size", kind: "word" },
  { prop: "selfAlignment", axis: "m4-self-alignment", kind: "word" },
  { prop: "gridPlacement", axis: "m5-grid-placement", kind: "word" },
  { prop: "gap", axis: "density", kind: "step-prefix", prefix: "gap" },
  { prop: "flow", axis: "flow-spacing", kind: "step-prefix", prefix: "flow" },
  { prop: "padding", axis: "padding", kind: "step-prefix", prefix: "padding" },
  { prop: "paddingInline", axis: "padding", kind: "step-prefix", prefix: "padding-inline" },
  { prop: "paddingBlock", axis: "padding", kind: "step-prefix", prefix: "padding-block" },
  { prop: "margin", axis: "margin", kind: "step-prefix", prefix: "margin" },
  { prop: "marginInline", axis: "margin", kind: "step-prefix", prefix: "margin-inline" },
  { prop: "marginBlock", axis: "margin", kind: "step-prefix", prefix: "margin-block" },
  { prop: "align", axis: "alignment-container", kind: "word" },
  { prop: "justify", axis: "alignment-container", kind: "word" },
  { prop: "divider", axis: "divider", kind: "word" },
  { prop: "wrapping", axis: "wrapping", kind: "word" },
  { prop: "overflow", axis: "overflow", kind: "word" },
  { prop: "overflowX", axis: "overflow", kind: "word" },
  { prop: "overflowY", axis: "overflow", kind: "word" },
  { prop: "minWidth", axis: "constraints", kind: "step-prefix", prefix: "min-width" },
  { prop: "maxWidth", axis: "constraints", kind: "step-prefix", prefix: "max-width" },
  { prop: "minHeight", axis: "constraints", kind: "step-prefix", prefix: "min-height" },
  { prop: "maxHeight", axis: "constraints", kind: "step-prefix", prefix: "max-height" },
  { prop: "zScale", axis: "z-scale", kind: "word" },
  { prop: "topLayerMechanism", axis: "top-layer-mechanism", kind: "word" },
  { prop: "positionMode", axis: "position-mode", kind: "word" },
  { prop: "stackingContext", axis: "stacking-context", kind: "word" },
  { prop: "motionMicro", axis: "motion-micro", kind: "word" },
  { prop: "motionMacro", axis: "motion-macro", kind: "word" },
  { prop: "focus", axis: "state.focus", kind: "group", many: true },
  { prop: "selection", axis: "state.selection", kind: "group", many: true },
  { prop: "availability", axis: "state.availability", kind: "group", many: true },
  { prop: "disclosure", axis: "state.disclosure", kind: "group" },
  { prop: "validity", axis: "state.validity", kind: "group", many: true },
  { prop: "sort", axis: "state.sort", kind: "group", many: true },
  { prop: "drag", axis: "state.drag", kind: "group", many: true },
  { prop: "continuousInput", axis: "state.continuous-input", kind: "group", many: true },
  { prop: "relational", axis: "state.relational", kind: "group", many: true },
  { prop: "skinGround", axis: "skin-ground", kind: "word" },
  { prop: "skinInk", axis: "skin-ink", kind: "word" },
  { prop: "skinRule", axis: "skin-rule", kind: "word" },
  { prop: "corner", axis: "corner", kind: "word" },
  { prop: "fontSize", axis: "font-size", kind: "word" },
  { prop: "fontWeight", axis: "font-weight", kind: "word" },
  { prop: "selectionTreatment", axis: "selection-treatment", kind: "word" },
];

export const SCOPE_DESCRIPTORS: readonly { prop: string; prefix: string }[] = [
  { prop: "viewportSm", prefix: "viewport-sm" },
  { prop: "viewportMd", prefix: "viewport-md" },
  { prop: "viewportLg", prefix: "viewport-lg" },
  { prop: "viewportXl", prefix: "viewport-xl" },
  { prop: "viewportPortrait", prefix: "viewport-portrait" },
  { prop: "viewportLandscape", prefix: "viewport-landscape" },
  { prop: "containerSm", prefix: "container-sm" },
  { prop: "containerMd", prefix: "container-md" },
  { prop: "containerLg", prefix: "container-lg" },
  { prop: "containerXl", prefix: "container-xl" },
  { prop: "prefersReducedMotion", prefix: "prefers-reduced-motion" },
  { prop: "prefersColorSchemeDark", prefix: "prefers-color-scheme-dark" },
  { prop: "prefersContrastMore", prefix: "prefers-contrast-more" },
  { prop: "prefersReducedTransparency", prefix: "prefers-reduced-transparency" },
];

export const XOR_PROPS: ReadonlySet<string> = new Set(["flex","grow","shrink","padding","paddingInline","paddingBlock","margin","marginInline","marginBlock","overflow","overflowX","overflowY"]);
