// surfaces/vite-plugin/index.ts — D3: JIT Ermine emission for Vite. Scans the
// configured content files for grammar words and writes ONLY the authored
// subset as one stylesheet. Lint findings on resolved-but-malformed
// compositions surface as build WARNINGS with the linter's reason text — never
// build failures (the page author may be mid-edit).
//
// `vite` is imported as a type only; at runtime the plugin uses whatever Vite
// instance loads it, keeping this package dependency-light and the core at
// zero runtime deps.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import type { Plugin } from "vite";

import { buildStylesheetWithCombines, parseAndNormalizeCombines, type CombineDocument } from "../../src/combines.ts";
import { buildStylesheet } from "../../src/css.ts";
import { formatWarning, scanSources, type ScanWarning } from "./scan.ts";

export interface ErmineOptions {
  /** files to scan for class attributes, relative to the Vite root */
  content: readonly string[];
  /** output stylesheet path, relative to the Vite root */
  outFile?: string;
  /** optional combine definition file, relative to the Vite root */
  combines?: string;
}

const HEADER = "/* GENERATED by @ermine/vite-plugin — do not edit by hand. */\n\n";

export function ermine(options: ErmineOptions): Plugin {
  const outFile = options.outFile ?? "ermine.generated.css";
  let root = process.cwd();

  function compile(): { css: string; warnings: ScanWarning[] } {
    const combines: CombineDocument | undefined = options.combines
      ? parseAndNormalizeCombines(readFileSync(resolve(root, options.combines), "utf8"), { sourceName: options.combines })
      : undefined;
    const sources = options.content.map((file) => ({
      file,
      content: readFileSync(resolve(root, file), "utf8"),
    }));
    const { elements, warnings } = scanSources(sources, { combines });
    const body = combines ? buildStylesheetWithCombines(elements, combines) : buildStylesheet(elements);
    return { css: `${HEADER}${body}`, warnings };
  }

  return {
    name: "ermine",

    configResolved(config) {
      root = config.root;
    },

    // build path (also runs once at dev-server start)
    buildStart() {
      const { css, warnings } = compile();
      for (const warning of warnings) this.warn(formatWarning(warning));
      writeFileSync(resolve(root, outFile), css);
    },

    // dev path: re-emit whenever a scanned content file changes
    configureServer(server) {
      const watched = [...options.content, ...(options.combines ? [options.combines] : [])].map((file) => resolve(root, file));
      server.watcher.add([...watched]);
      server.watcher.on("change", (changed) => {
        if (!watched.includes(changed)) return;
        const { css, warnings } = compile();
        for (const warning of warnings) server.config.logger.warn(formatWarning(warning));
        writeFileSync(resolve(root, outFile), css);
        server.ws.send({ type: "full-reload" });
      });
    },
  };
}
