// Compiles a project's socket palette to theme CSS: one scoped block per theme × mode,
// resolved through the real theme plane (R-SKIN-08). This is the theme counterpart to
// adoption/build-css.ts — a project owns the palette; Ermine emits the derived CSS. The
// palette module exports `palettes: Palette`. `--check` fails if the output is stale.
//
//   node --import tsx adoption/build-theme-css.ts \
//     --palette <palette.ts> --out <theme.generated.css> [--scope ":root"] [--check]

import { readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";

import { resolveTheme, validateBindings, type Mode, type Palette } from "../src/theme/theme-plane.ts";

function flag(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

const palettePath = flag("--palette");
const outPath = flag("--out");
const scope = flag("--scope") ?? ":root";
const check = process.argv.includes("--check");

if (!palettePath || !outPath) {
  console.error("usage: --palette <file> --out <file> [--scope <selector>] [--check]");
  process.exit(2);
}

const module = (await import(pathToFileURL(palettePath).href)) as { palettes?: Palette; default?: Palette };
const palettes = module.palettes ?? module.default;
if (!palettes) {
  console.error(`${palettePath} must export \`palettes\` (or a default) of type Palette`);
  process.exit(2);
}

const modes: Mode[] = ["light", "dark"];
let css = "/* GENERATED by adoption/build-theme-css.ts from the socket palette — do not edit. */\n";
for (const theme of Object.keys(palettes)) {
  for (const mode of modes) {
    const bindings = resolveTheme(palettes, theme, mode);
    const errors = validateBindings(bindings);
    if (errors.length) {
      console.error(`palette ${theme}/${mode} fails the contract:\n  ${errors.join("\n  ")}`);
      process.exit(1);
    }
    const decls = Object.entries(bindings)
      .map(([socket, value]) => `  --${socket}: ${value};`)
      .join("\n");
    css += `\n${scope}[data-theme="${theme}"][data-mode="${mode}"] {\n${decls}\n}\n`;
  }
}

const outUrl = pathToFileURL(outPath);
const current = await readFile(outUrl, "utf8").catch(() => "");

if (check) {
  if (current !== css) {
    console.error(`${outPath} is stale; regenerate the theme CSS`);
    process.exitCode = 1;
  } else {
    console.log(`${outPath} is current`);
  }
} else if (current !== css) {
  await writeFile(outUrl, css);
  console.log(`wrote ${outPath} — ${Object.keys(palettes).length} themes × ${modes.length} modes`);
} else {
  console.log(`${outPath} already current`);
}
