// make-original.ts — reproducible provenance for original.html (C4 step 1).
// Generates a REAL Playwright HTML report (the C2 corpus target with the
// highest layer-1 coverage: 82.4%) by running the two-spec sample suite below
// through the bundled test runner, renders it in Chromium, and snapshots the
// rendered DOM as a static page whose only styling is the committed corpus
// stylesheet. Scripts and injected styles are stripped so the pair
// original.html / translated.html differ ONLY in class attribution + CSS.
//
// Reproduce: npm run translate:original

import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { chromium } from "playwright";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const REPO = fileURLToPath(new URL("../..", import.meta.url));

async function main(): Promise<void> {
  const workDir = mkdtempSync(join(tmpdir(), "c4-report-"));
  try {
    const run = spawnSync("npx", [
      "playwright", "test",
      "--config", join(HERE, "page-source", "pw.config.ts"),
      "--output", join(workDir, "test-results"),
    ], {
      cwd: REPO,
      env: { ...process.env, C4_REPORT_DIR: join(workDir, "html-report") },
      encoding: "utf8",
    });
    if (run.status !== 0) throw new Error(`report generation failed:\n${run.stdout}\n${run.stderr}`);

    const browser = await chromium.launch({ args: ["--no-sandbox"] });
    try {
      const page = await browser.newPage();
      await page.goto(pathToFileURL(join(workDir, "html-report", "index.html")).href);
      await page.waitForSelector(".test-file-test", { timeout: 15_000 });
      const body = await page.evaluate(() => {
        for (const node of document.querySelectorAll("script, style, link")) node.remove();
        return document.body.outerHTML;
      });

      const html = `<!DOCTYPE html>
<!-- Rendered-DOM snapshot of a real Playwright HTML report (playwright@1.61.1),
     generated by analysis/translation/make-original.ts from the committed
     two-spec sample suite. Scripts and injected styles stripped; styling comes
     solely from the committed corpus stylesheet. C4 page choice: highest
     layer-1 coverage in the C2 corpus (82.4%). -->
<html>
<head>
<meta charset="utf-8">
<title>C4 original — Playwright HTML report snapshot</title>
<link rel="stylesheet" href="../corpus/playwright-html-report/report.css">
</head>
${body}
</html>
`;
      await mkdir(HERE, { recursive: true });
      await writeFile(join(HERE, "original.html"), html);
      console.log(`wrote analysis/translation/original.html (${html.length} bytes)`);
    } finally {
      await browser.close();
    }
  } finally {
    rmSync(workDir, { recursive: true, force: true });
  }
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
