// D4 editor data: registry vocabulary + existing guide glosses → stable JSON.
// Descriptions are assembled only from generated guide blocks, registry notes,
// and token shape strings. This generator does not author vocabulary prose.

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

import type { AxisRecord } from "../../engine/types.ts";
import { emittableWords } from "../../src/derive-ownership.ts";
import { emit } from "../../src/emit.ts";
import type { EmittedRule } from "../../src/emitter-types.ts";
import { parseWord } from "../../src/lint.ts";
import { ENVIRONMENT_SCOPES, INTERACTION_SCOPES, REGISTRY, RELATIONAL_SCOPES, SCALES, STATE_SCOPES } from "../../src/registry.ts";
import type {
  CompletionAxis,
  CompletionData,
  CompletionEntry,
  ExplanationData,
  ExplanationEmission,
  ExplanationEntry,
  HoverData,
  HoverEntry,
  PatternExplanation,
  PatternHover,
} from "./data.ts";

const GUIDE = new URL("../../src/ERMINE-GUIDE.md", import.meta.url);
const COMPLETIONS = new URL("./completions.generated.json", import.meta.url);
const HOVERS = new URL("./hovers.generated.json", import.meta.url);
const EXPLANATIONS = new URL("./explanations.generated.json", import.meta.url);
const GENERATED_NOTE = "Generated by surfaces/vscode/generate-data.ts — do not edit.";

const SECTION_BY_SIBLING: Record<AxisRecord["sibling"], string> = {
  layout: "2.1",
  layering: "2.2",
  motion: "2.3",
  state: "2.4",
  skin: "2.5",
};
const ALL_SCOPES = [...ENVIRONMENT_SCOPES, ...INTERACTION_SCOPES, ...STATE_SCOPES, ...RELATIONAL_SCOPES];

interface GuideGlosses {
  exact: Map<string, string>;
  prefixes: Array<[string, string]>;
}

function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function logicalBullets(block: string): string[] {
  const bullets: string[] = [];
  for (const line of block.split("\n")) {
    if (line.startsWith("- ")) bullets.push(line);
    else if (bullets.length && /^\s+\S/.test(line)) bullets[bullets.length - 1] += ` ${line.trim()}`;
  }
  return bullets;
}

function expandCompact(expression: string): string[] {
  if (expression.endsWith("*")) return [];
  const parts = expression.split("|");
  if (parts.length === 1) return [expression];
  const first = parts[0];
  const split = first.lastIndexOf("-");
  const prefix = split >= 0 ? first.slice(0, split + 1) : "";
  return [first, ...parts.slice(1).map((part) => part.includes("-") ? part : `${prefix}${part}`)];
}

export function extractGuideGlosses(source: string): GuideGlosses {
  const exact = new Map<string, string>();
  const prefixes: Array<[string, string]> = [];
  const blocks = source.matchAll(
    /<!-- BEGIN GENERATED: guide-[^\n]+ -->\n([\s\S]*?)\n<!-- END GENERATED: guide-[^\n]+ -->/g,
  );

  for (const block of blocks) {
    for (const bullet of logicalBullets(block[1])) {
      const separator = bullet.indexOf(" — ");
      const head = separator >= 0 ? bullet.slice(2, separator) : bullet.slice(2);
      const meaning = oneLine(separator >= 0 ? bullet.slice(separator + 3) : bullet.slice(2));
      for (const match of head.matchAll(/`([^`]+)`/g)) {
        const expression = match[1];
        exact.set(expression, meaning);
        if (expression.endsWith("*")) {
          prefixes.push([expression.slice(0, -1), meaning]);
        } else {
          for (const word of expandCompact(expression)) exact.set(word, meaning);
        }
      }
    }
  }
  prefixes.sort((left, right) => right[0].length - left[0].length);
  return { exact, prefixes };
}

function guideMeaning(word: string, glosses: GuideGlosses): string | undefined {
  const exact = glosses.exact.get(word);
  if (exact) return exact;
  return glosses.prefixes.find(([prefix]) => word.startsWith(prefix))?.[1];
}

function matchedToken(record: AxisRecord, word: string) {
  return record.tokens.find((token) => !token.fallback && token.pattern.test(word));
}

function meaningFor(word: string, record: AxisRecord, glosses: GuideGlosses): string {
  const fromGuide = guideMeaning(word, glosses);
  if (fromGuide) return fromGuide;
  const stateWord = word.includes("-")
    ? record.stateGroup?.members.find((member) => word === member.word || word.startsWith(`${member.word}-`))
    : record.stateGroup?.members.find((member) => word === member.word);
  return oneLine(stateWord?.note ?? record.notes ?? matchedToken(record, word)?.shape ?? record.tokens[0]?.shape ?? record.axis);
}

function referenceFor(record: AxisRecord): string {
  return `src/ERMINE-SPEC.md §${SECTION_BY_SIBLING[record.sibling]} — ${record.axis}`;
}

function explanationEmission(rule: EmittedRule): ExplanationEmission {
  if (rule.kind === "declares") {
    return {
      kind: rule.kind,
      axis: rule.axis,
      token: rule.token,
      selector: rule.selector,
      declarations: rule.declarations,
    };
  }
  if (rule.kind === "reads") {
    return {
      kind: rule.kind,
      selector: rule.selector,
      declarations: rule.declarations,
      reads: rule.reads,
    };
  }
  if (rule.kind === "facet") {
    return {
      kind: rule.kind,
      axis: rule.axis,
      token: rule.token,
      selector: rule.selector,
      property: rule.property,
      facet: rule.facet,
      value: rule.value,
    };
  }
  if (rule.kind === "condition") {
    return {
      kind: rule.kind,
      axis: rule.axis,
      token: rule.token,
      selectorFragment: rule.selectorFragment,
    };
  }
  return {
    kind: rule.kind,
    axis: rule.axis,
    token: rule.token,
    mechanism: rule.mechanism,
  };
}

function numericPrefixes(record: AxisRecord): string[] {
  return record.valueSpace
    .filter((value) => value.endsWith("-N"))
    .map((value) => value.slice(0, -1));
}

function concreteWords(record: AxisRecord, words: Record<string, string[]>): string[] {
  const prefixes = numericPrefixes(record);
  return (words[record.axis] ?? []).filter((word) => !prefixes.some((prefix) => {
    if (!word.startsWith(prefix)) return false;
    return /^\d+$/.test(word.slice(prefix.length));
  }));
}

interface SnippetShape { label: string; choices?: readonly string[] }

function snippetShapes(record: AxisRecord): SnippetShape[] {
  if (!record.tokens.some((token) => !token.fallback)) return [];
  const found = new Map<string, SnippetShape>();
  const add = (label: string, choices?: readonly string[]) => {
    if (!found.has(label)) found.set(label, { label, choices });
  };

  for (const value of record.valueSpace) {
    if (value.endsWith("-N")) add(value);
    const placeholder = value.match(/<([^>]+)>/i)?.[1];
    if (placeholder === "size") add(value, SCALES.size);
    if (placeholder === "spacing") add(value, SCALES.spacing);
  }

  for (const token of record.tokens) {
    if (token.fallback) continue;
    for (const shape of token.shape.split(" | ")) {
      if (/^[a-z][a-z-]*-<spacing>$/.test(shape)) add(shape, SCALES.spacing);
      if (/^[a-z][a-z-]*-<size>$/.test(shape)) add(shape, SCALES.size);
    }
  }

  for (const member of record.stateGroup?.members ?? []) {
    if (member.enumValues?.length) add(`${member.word}-<value>`, member.enumValues);
  }
  return [...found.values()];
}

function snippetText(shape: SnippetShape): string {
  if (shape.label.endsWith("-N")) return shape.label.replace(/N$/, "${1:1}");
  if (shape.choices?.length) {
    return shape.label.replace(/<[^>]+>/, `\${1|${shape.choices.join(",")}|}`);
  }
  throw new Error(`Cannot render editor placeholder for ${shape.label}`);
}

function completionAxis(
  record: AxisRecord,
  words: Record<string, string[]>,
  glosses: GuideGlosses,
): CompletionAxis | null {
  const items: CompletionEntry[] = concreteWords(record, words).map((word) => ({
    label: word,
    insertText: word,
    kind: "word",
    meaning: meaningFor(word, record, glosses),
  }));
  for (const shape of snippetShapes(record)) {
    items.push({
      label: shape.label,
      insertText: snippetText(shape),
      kind: "snippet",
      meaning: meaningFor(shape.label, record, glosses),
    });
  }
  return items.length ? { axis: record.axis, reference: referenceFor(record), items } : null;
}

export function renderData(guideSource: string): { completions: CompletionData; hovers: HoverData; explanations: ExplanationData } {
  const glosses = extractGuideGlosses(guideSource);
  const words = emittableWords();
  const axes = REGISTRY
    .map((record) => completionAxis(record, words, glosses))
    .filter((axis): axis is CompletionAxis => axis !== null);

  const hoverWords: Record<string, HoverEntry> = {};
  for (const axis of axes) {
    for (const item of axis.items) {
      if (item.kind === "snippet") continue;
      hoverWords[item.label] = { axis: axis.axis, meaning: item.meaning, reference: axis.reference };
    }
  }

  const patterns: PatternHover[] = [];
  const explanationPatterns: PatternExplanation[] = [];
  for (const record of REGISTRY) {
    for (const token of record.tokens) {
      if (token.fallback || !token.valueDomain) continue;
      patterns.push({
        pattern: token.pattern.source,
        axis: record.axis,
        meaning: oneLine(record.notes ?? token.shape),
        reference: referenceFor(record),
      });
      explanationPatterns.push({
        pattern: token.pattern.source,
        axis: record.axis,
        sibling: record.sibling,
        role: record.role,
        signature: record.signature,
        member: null,
        meaning: oneLine(record.notes ?? token.shape),
        reference: referenceFor(record),
        emissions: [],
      });
    }
  }

  const explanationWords: Record<string, ExplanationEntry> = {};
  for (const record of REGISTRY) {
    for (const word of concreteWords(record, words)) {
      const parsed = parseWord(word);
      explanationWords[word] = {
        axis: record.axis,
        sibling: record.sibling,
        role: record.role,
        signature: record.signature,
        member: parsed.member,
        ...(parsed.dial !== undefined ? { dial: parsed.dial } : {}),
        meaning: meaningFor(word, record, glosses),
        reference: referenceFor(record),
        emissions: emit(word).map(explanationEmission),
      };
    }
  }

  const explanations: ExplanationData = {
    _generated: [
      GENERATED_NOTE,
      "Derived cache from REGISTRY, ERMINE-GUIDE.md, parseWord(), and emit(); npm run vscode:check verifies it.",
    ],
    scopes: ALL_SCOPES.map((scope) => scope.pattern.source),
    axisOrder: REGISTRY.map((record) => record.axis),
    words: explanationWords,
    patterns: explanationPatterns,
  };

  return {
    completions: { _generated: [GENERATED_NOTE], axes },
    hovers: {
      _generated: [GENERATED_NOTE],
      scopes: ALL_SCOPES.map((scope) => scope.pattern.source),
      words: hoverWords,
      patterns,
    },
    explanations,
  };
}

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function firstDifference(current: string, expected: string): string {
  const left = current.split("\n");
  const right = expected.split("\n");
  for (let index = 0; index < Math.max(left.length, right.length); index += 1) {
    if (left[index] !== right[index]) {
      return `first difference at line ${index + 1}\n  current:  ${left[index] ?? "<EOF>"}\n  expected: ${right[index] ?? "<EOF>"}`;
    }
  }
  return "content differs";
}

async function main(): Promise<void> {
  const guide = await readFile(GUIDE, "utf8");
  const rendered = renderData(guide);
  const outputs = [
    { path: COMPLETIONS, content: json(rendered.completions) },
    { path: HOVERS, content: json(rendered.hovers) },
    { path: EXPLANATIONS, content: json(rendered.explanations) },
  ];
  const check = process.argv.includes("--check");

  for (const output of outputs) {
    const current = await readFile(output.path, "utf8").catch((cause: unknown) => {
      if ((cause as NodeJS.ErrnoException).code === "ENOENT") return "";
      throw cause;
    });
    if (check && current !== output.content) {
      console.error(`${output.path.pathname.split("/").pop()} is stale; run npm run vscode\n${firstDifference(current, output.content)}`);
      process.exitCode = 1;
    } else if (!check && current !== output.content) {
      await writeFile(output.path, output.content);
      console.log(`updated ${output.path.pathname}`);
    } else {
      console.log(`${output.path.pathname.split("/").pop()} is current`);
    }
  }
}

const invoked = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";
if (import.meta.url === invoked) await main();
