// build.ts — the JIT pipeline in miniature: scan the fixture's markup for the
// class strings actually used, compile only those to CSS. `pnpm demo`.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { buildStylesheet } from "../src/css.ts";

const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, "index.html"), "utf8");

// each element's class attribute is one class string (facets/sinks are per-element).
const classStrings = [...html.matchAll(/class="([^"]+)"/g)].map((m) => m[1]);
const css = buildStylesheet(classStrings);

writeFileSync(join(here, "ermine.css"),
  `/* GENERATED by \`pnpm demo\` from index.html — do not edit by hand. */\n\n${css}`);

console.log(`wrote demo/ermine.css from ${classStrings.length} class strings (${new Set(classStrings).size} unique).`);
console.log(`open demo/index.html in a browser; swap theme.css → theme-alt.css to re-skin.`);
