// Runs the real theme plane over the sample palettes and writes one scoped block per
// theme × mode to demo/theme-plane.generated.css. The demo page switches by flipping
// data-theme / data-mode on <html>, so the plane's resolution drives a live re-skin.
// `npm run theme-demo`.

import { writeFileSync } from "node:fs";

import { resolveTheme, validateBindings, type Mode } from "../src/theme/theme-plane.ts";
import { palettes } from "./theme-palettes.ts";

const OUT = new URL("./theme-plane.generated.css", import.meta.url);
const modes: Mode[] = ["light", "dark"];

let css = "/* GENERATED by `npm run theme-demo` from the theme plane — do not edit. */\n";
for (const theme of Object.keys(palettes)) {
  for (const mode of modes) {
    const bindings = resolveTheme(palettes, theme, mode);
    const errors = validateBindings(bindings);
    if (errors.length) {
      console.error(`palette ${theme}/${mode} fails the contract:\n  ${errors.join("\n  ")}`);
      process.exit(1);
    }
    const decls = Object.entries(bindings)
      .map(([socket, value]) => `  --${socket}: ${value};`)
      .join("\n");
    css += `\n.theme-root[data-theme="${theme}"][data-mode="${mode}"] {\n${decls}\n}\n`;
  }
}

writeFileSync(OUT, css);
console.log(
  `wrote ${OUT.pathname} — ${Object.keys(palettes).length} themes × ${modes.length} modes, all contract-valid.`,
);
