import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

import { deriveControls } from "./emitter-types.ts";
import { COMPOSED_PROOFS, emit, VOCABULARY } from "./emit.ts";
import { REGISTRY } from "./registry.ts";

const OWNERSHIP_PATH = new URL("./ownership.generated.json", import.meta.url);
export const GENERATED_KEY = "_generated";
export const GENERATED_NOTE = "Generated by src/derive-ownership.ts — do not edit.";

export type OwnershipMap = Record<string, string[]>;

function stateWords(): Record<string, string[]> {
  return Object.fromEntries(REGISTRY.filter((axis) => axis.stateGroup).map((axis) => [
    axis.axis,
    axis.stateGroup!.members.flatMap((member) =>
      member.arity === "enumerated"
        ? (member.enumValues ?? []).map((value) => `${member.word}-${value}`)
        : [member.word]),
  ]));
}

export function emittableWords(): Record<string, string[]> {
  return { ...VOCABULARY, ...stateWords() };
}

export function deriveOwnership(): OwnershipMap {
  const words = emittableWords();
  const batches = [
    ...Object.values(words).flat().map((word) => emit(word)),
    ...COMPOSED_PROOFS.map((classString) => emit(classString)),
  ];
  const { paints } = deriveControls(batches.flat());

  return Object.fromEntries(REGISTRY
    .filter((axis) => Object.hasOwn(words, axis.axis))
    .map((axis) => [axis.axis, [...(paints[axis.axis] ?? [])].sort()]));
}

export function renderOwnership(ownership = deriveOwnership()): string {
  return `${JSON.stringify({ [GENERATED_KEY]: [GENERATED_NOTE], ...ownership }, null, 2)}\n`;
}

function firstDifference(current: string, expected: string): string {
  const currentLines = current.split("\n");
  const expectedLines = expected.split("\n");
  const length = Math.max(currentLines.length, expectedLines.length);
  for (let index = 0; index < length; index += 1) {
    if (currentLines[index] !== expectedLines[index]) {
      return [
        `first difference at line ${index + 1}`,
        `  current:  ${currentLines[index] ?? "<EOF>"}`,
        `  expected: ${expectedLines[index] ?? "<EOF>"}`,
      ].join("\n");
    }
  }
  return "content differs";
}

async function run(): Promise<void> {
  const expected = renderOwnership();
  const check = process.argv.includes("--check");
  let current = "";
  try {
    current = await readFile(OWNERSHIP_PATH, "utf8");
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code !== "ENOENT") throw cause;
  }

  if (check) {
    if (current !== expected) {
      console.error(`ownership.generated.json is stale; run npm run ownership\n${firstDifference(current, expected)}`);
      process.exitCode = 1;
    } else {
      console.log("ownership.generated.json is current");
    }
  } else if (current !== expected) {
    await writeFile(OWNERSHIP_PATH, expected);
    console.log(`updated ${OWNERSHIP_PATH.pathname}`);
  } else {
    console.log("ownership.generated.json already current");
  }
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";
if (import.meta.url === invokedPath) await run();
